-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.8"

ideasRevision :: String
ideasRevision = "26fe80bf0f02342b55587676d6d34fd4bbcd3cad"

ideasLastChanged :: String
ideasLastChanged = "Mon Sep 9 12:42:00 2019 +0200"
